-- Fix It database schema (9 tables). See Specifications_and_designs/Fix_It_Database_Design.md
-- Apply with: psql -d fix_it -f db/schema.sql

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    smail         VARCHAR(255) NOT NULL UNIQUE,
    -- Username + password login (temporary alternative to Google sign-in). Both are NULL for accounts created by
    -- Google sign-in. DEVIATION from Fix_It_Database_Design.md, which stores no password: only a BCrypt hash is stored.
    username      VARCHAR(30),
    password_hash VARCHAR(100),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Usernames are unique ignoring case ("Alice" == "alice"); NULLs (Google-only accounts) do not conflict
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));

CREATE TABLE questions (
    question_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id          BIGINT NOT NULL REFERENCES users (user_id),
    title              VARCHAR(255) NOT NULL,
    body               TEXT NOT NULL,
    is_resolved        BOOLEAN NOT NULL DEFAULT FALSE,
    accepted_answer_id BIGINT,           -- FK to answers added below (circular reference)
    interest_count     INT NOT NULL DEFAULT 0 CHECK (interest_count >= 0),
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL UNIQUE
);

-- Tag names are unique ignoring case ("WiFi" == "wifi")
CREATE UNIQUE INDEX uq_tags_name_lower ON tags (lower(name));

-- The fixed set of tags (the application, app.tags.allowed, only accepts these; it also re-creates them at startup if missing)
INSERT INTO tags (name) VALUES ('tech'), ('math'), ('code'), ('others') ON CONFLICT DO NOTHING;

CREATE TABLE question_tags (
    question_id BIGINT NOT NULL REFERENCES questions (question_id),
    tag_id      BIGINT NOT NULL REFERENCES tags (tag_id),
    PRIMARY KEY (question_id, tag_id)
);

CREATE TABLE answers (
    answer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions (question_id),
    author_id   BIGINT NOT NULL REFERENCES users (user_id),
    body        TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- lets questions reference (answer, question) so an accepted answer must belong to its question
    UNIQUE (answer_id, question_id)
);

-- Accepted answer must belong to the same question. Nullable: unresolved questions skip the check.
ALTER TABLE questions
    ADD CONSTRAINT fk_questions_accepted_answer
    FOREIGN KEY (accepted_answer_id, question_id) REFERENCES answers (answer_id, question_id);

CREATE TABLE question_comments (
    comment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id       BIGINT NOT NULL REFERENCES questions (question_id),
    author_id         BIGINT NOT NULL REFERENCES users (user_id),
    parent_comment_id BIGINT,
    body              TEXT NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (comment_id, question_id),
    -- a reply must be on the same question as its parent
    FOREIGN KEY (parent_comment_id, question_id) REFERENCES question_comments (comment_id, question_id)
);

CREATE TABLE question_comment_votes (
    comment_id BIGINT NOT NULL REFERENCES question_comments (comment_id),
    user_id    BIGINT NOT NULL REFERENCES users (user_id),
    vote_type  VARCHAR(4) NOT NULL CHECK (vote_type IN ('UP', 'DOWN')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE question_interests (
    question_id BIGINT NOT NULL REFERENCES questions (question_id),
    user_id     BIGINT NOT NULL REFERENCES users (user_id),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (question_id, user_id)
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (user_id),
    type            VARCHAR(50) NOT NULL,
    question_id     BIGINT NOT NULL REFERENCES questions (question_id),
    comment_id      BIGINT REFERENCES question_comments (comment_id),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------------------------------------
-- Derived search data (NOT one of the 9 design tables; the design defines no embedding storage).
-- One embedding per question, rebuilt from the question text at any time.
--  * `embedding` is deliberately an UNSIZED vector: the model/dimension is not decided yet.
--    The app only compares vectors whose model and dimension match the current configuration.
--  * `model` records which model produced the vector (vectors from different models are not comparable).
--  * `text_hash` is the SHA-256 of the exact text that was embedded, to detect stale vectors.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE question_embeddings (
    question_id BIGINT PRIMARY KEY REFERENCES questions (question_id),
    embedding   vector NOT NULL,
    model       VARCHAR(200) NOT NULL,
    text_hash   CHAR(64) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
